
package org.arpit.javapostsforlearning.webservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://webservices.javapostsforlearning.arpit.org")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "sayHelloWorldReturn", targetNamespace = "http://webservices.javapostsforlearning.arpit.org")
    @RequestWrapper(localName = "sayHelloWorld", targetNamespace = "http://webservices.javapostsforlearning.arpit.org", className = "org.arpit.javapostsforlearning.webservices.SayHelloWorld")
    @ResponseWrapper(localName = "sayHelloWorldResponse", targetNamespace = "http://webservices.javapostsforlearning.arpit.org", className = "org.arpit.javapostsforlearning.webservices.SayHelloWorldResponse")
    public String sayHelloWorld(
        @WebParam(name = "name", targetNamespace = "http://webservices.javapostsforlearning.arpit.org")
        String name);

}
